### ISSUE TITLE
Cyborg theme tweaks

### ISSUE THREAD

**Issue by whjms** [apxltd/what-bugs#165]
Fix replies label:

```css
.topic [component="post/parent"] {
     background-color: #333;
}
```

![image](https://user-images.githubusercontent.com/3392687/30526574-92c0ea8e-9bea-11e7-9792-3db4e44e0240.png)

![image](https://user-images.githubusercontent.com/3392687/30526583-be7fd73e-9bea-11e7-915a-6176129a5a90.png)

Fix notification color:

```css
body.skin-cyborg .header .notification-list li.unread {
    background-color: #565656;
}
```

![image](https://user-images.githubusercontent.com/3392687/30526613-8456ddfe-9beb-11e7-91bd-da2f520e2204.png)

![image](https://user-images.githubusercontent.com/3392687/30526609-784171dc-9beb-11e7-92ea-6cc58ea29d1e.png)
